### ISSUE TITLE
Error when running first.py

### ISSUE THREAD

**Issue by lenhattu** [hypernovas/lipfuzzer#1]
Which version of Python is this?
The syntax looks like Python 2 so I tried Python 2.7.15. However, I got AttributeError: 'module' object has no attribute 'DEVNULL' when running first.py
Thank you.

**Comment by hypernovas** [comment]
Hi, we noticed the issue and this should be caused by newer NLTK version. We used 2.7.15 and it seems no longer compatible with NLTK. We are investigating the problem and will release an updated Lipfuzzer asap.

**Comment by hypernovas** [comment]
Hi, the problem is solved and Lipfuzzer is now running python3. Thank you for the feedback.
